b_io/models.py
import datetime
import json
import re
from pathlib import Path

import toml
import nbformat
from dateutil.parser import parse as dt_parse
from nbconvert import HTMLExporter

from flask import current_app, url_for

RE_FOLDER = re.compile(
    r"^(?P<year>\d{4})-(?P<month>\d{2})-(?P<day>\d{2})-" r"(?P<slug>[-\w]+)$"
)


class Mention(object):
    """Braithwaite I/O Mention Entry."""

    @classmethod
    def parse(cls, path):
        """Parse the mention."""
        with open(path) as fobj:
            data = json.loads(fobj.read())

        mention = cls()
        setattr(mention, "_json", data)

        for k, v in data.items():
            if k == "verified_date":
                setattr(mention, k, dt_parse(v))
            else:
                setattr(mention, k, v)

        return mention


class Notebook(object):
    """Braithwaite I/O Notebook Entry."""

    def __init__(self, path):
        self.path = Path(path)
        self.mention_path = self.path.joinpath("_mentions")

        meta_path = self.path.joinpath("meta.toml")

        if meta_path.is_file():
            with open(meta_path) as fobj:
                self.__meta = toml.loads(fobj.read())
        else:
            self.__meta = {}

        notebook_path = self.path.joinpath("notebook.ipynb")

        with open(notebook_path) as fobj:
            notebook = nbformat.reads(fobj.read(), as_version=4)

        html_exporter = HTMLExporter(
            template_path=[str(current_app.config["TEMPLATES_FOLDER"])]
        )
        html_exporter.template_file = "nbconvert"

        (self.__body, self.__resources) = html_exporter.from_notebook_node(
            notebook
        )

    @property
    def name(self):
        if self.__meta.get("name"):
            return self.__meta.get("name")
        else:
            match = RE_FOLDER.match(self.path.name).groupdict()
            return match["slug"].replace("-", " ")

    @property
    def published(self):
        if self.__meta.get("published"):
            return self.__meta.get("published")
        else:
            match = RE_FOLDER.match(self.path.name).groupdict()
            return datetime.datetime.strptime(
                "{year}-{month}-{day}".format(match), "%Y-%m-%d"
            )

    @property
    def updated(self):
        if self.__meta.get("updated"):
            return self.__meta.get("updated")

        match = RE_FOLDER.match(self.path.name).groupdict()

        return datetime.datetime.strptime(
            "{year}-{month}-{day}".format(**match), "%Y-%m-%d"
        )

    @property
    def hidden(self):
        return self.__meta.get("hidden", False)

    @property
    def category(self):
        return self.__meta.get("category")

    @property
    def summary(self):
        return self.__meta.get("summary")

    @property
    def content(self):
        return self.__body

    @property
    def slug(self):
        return self.path.name

    @property
    def url(self):
        return url_for("views.notebook", slug=self.slug)

    @property
    def notebook_url(self):
        return url_for("views.jupyter_notebook", slug=self.slug)

    @property
    def resources(self):
        return self.__resources

    def list_mentions(self):
        file_list = self.mention_path.glob("*.json")

        mentions = [Mention.parse(file_name) for file_name in file_list]

        mentions.sort(key=lambda x: x.verified_date, reverse=True)

        return mentions


def all_notebooks():
    def gen():
        content_path = Path(current_app.config["CONTENT_ROOT"])

        notebooks = content_path.glob("**/meta.toml")

        for path in notebooks:
            yield Notebook(path.parent)

    g = list(gen())
    g.sort(key=lambda x: x.published, reverse=True)

    return g


def all_mentions():
    def gen():
        content_path = Path(current_app.config["CONTENT_ROOT"])

        mentions = content_path.glob("**/_mentions/*.json")

        for mention in mentions:
            yield Mention(mention)

    g = list(gen())
    g.sort(key=lambda x: x.id, reversed=True)

    return g

b_io/__init__.py
# -*- coding: utf-8 -*-
"""Braithwaite I/O."""

__version__ = "1.0.0"

b_io/app.py
# -*- coding: utf-8 -*-
"""The app module, containing the app factory functions."""
from flask import Flask, render_template

from b_io import __version__
from b_io import commands, views
from b_io.extensions import debug_toolbar, webpack
from b_io.settings import ProdConfig


def create_app(config_obj=ProdConfig):
    """An application factory.

    Documentation: http://flask.pocoo.org/docs/patterns/appfactories/

    :param config_obj: The configuration object to use.
    """
    app = Flask(__name__.split(".")[0])
    app.config.from_object(config_obj)

    register_extensions(app)
    register_blueprints(app)
    register_errorhandlers(app)
    register_shellcontext(app)
    register_commands(app)
    register_context_processors(app)

    return app


def register_extensions(app):
    """Register Flask extensions."""
    debug_toolbar.init_app(app)
    webpack.init_app(app)

    return None


def register_blueprints(app):
    """Register Flask blueprints."""
    app.register_blueprint(views.blueprint)

    return None


def register_errorhandlers(app):
    """Register error handlers."""

    def render_error(error):
        """Render error template."""
        # If a HTTPException, pull the `code` attribute; default to 500
        error_code = getattr(error, "code", 500)
        return render_template("{0}.html".format(error_code)), error_code

    for errcode in [401, 404, 500]:
        app.errorhandler(errcode)(render_error)

    return None


def register_shellcontext(app):
    """Register shell context objects."""

    def shell_context():
        """Shell context objects."""
        return {}

    app.shell_context_processor(shell_context)


def register_commands(app):
    """Register Click commands."""
    app.cli.add_command(commands.test)
    app.cli.add_command(commands.lint)
    app.cli.add_command(commands.clean)
    app.cli.add_command(commands.urls)
    app.cli.add_command(commands.freeze)


def register_context_processors(app):
    """Register Context Processors."""

    def version():
        """Return the B I/O version."""
        return {"version": __version__}

    app.context_processor(version)

b_io/views.py
# -*- coding: utf-8 -*-
from pathlib import Path

from flask import Blueprint, abort, current_app, render_template, Response

from feedgenerator import Atom1Feed
from jsonfeed import JSONFeed

from .models import Notebook, all_notebooks

blueprint = Blueprint("views", __name__)


@blueprint.route("/")
def index():
    notebook_list = all_notebooks()

    return render_template("index.html", notebooks=notebook_list)


@blueprint.route("/feed.<string:feed_type>")
def feed(feed_type):
    if feed_type not in ["json", "xml"]:
        abort(404)

    author_info = {
        "author_name": "Myles Braithwaite",
        "author_link": "https://mylesb.ca/",
        "author_email": "me@mylesbraithwaite.org",
    }

    meta_info = {
        "title": "Braithwaite I/O",
        "link": "https://braithwaite.io/",
        "feed_guid": "https://braithwaite.io/",
        "description": "Myles Braithwaite's Fancy Jupyter Notebooks Blog.",
        "language": "en",
    }

    if feed_type == "json":
        feed = JSONFeed(**{**meta_info, **author_info})
        mimetype = feed.content_type
    else:
        feed = Atom1Feed(**meta_info)
        mimetype = "application/atom+xml"

    for notebook in all_notebooks():
        feed.add_item(
            guid="https://braithwaite.io{}".format(notebook.url),
            title=notebook.name,
            link="https://braithwaite.io{}".format(notebook.url),
            summary=notebook.summary,
            description=notebook.content,
            pubdate=notebook.published,
            categories=notebook.category,
            **author_info,
        )

    return Response(feed.writeString("utf-8"), mimetype=mimetype)


@blueprint.route("/<slug>/")
def notebook(slug):
    content_path = Path(current_app.config["CONTENT_ROOT"])

    try:
        notebook = Notebook(content_path.joinpath(slug))

        return render_template("notebook.html", notebook=notebook)
    except IOError:
        abort(404)


@blueprint.route("/<slug>/notebook.ipynb")
def jupyter_notebook(slug):
    content_path = Path(current_app.config["CONTENT_ROOT"])

    notebook_path = content_path.joinpath(slug, "notebook.ipynb")

    try:
        with open(notebook_path) as fobj:
            return Response(fobj.read(), mimetype="application/vnd.jupyter")
    except IOError:
        abort(404)

b_io/templates/base.html
<!DOCTYPE html>
<html lang="en">
    <head>
    {% block head %}
        <meta charset="utf-8">

        <title>{% block title %}Braithwaite I/O{% endblock %}</title>

        <meta name="viewport" content="width=device-width, initial-scale=1">

        <link href="https://fonts.googleapis.com/css?family=IBM+Plex+Mono|IBM+Plex+Sans|IBM+Plex+Serif:400,700" rel="stylesheet">
        <link rel="stylesheet" href="{{ asset_url_for('main.css') }}">

        <link rel="icon" href="{{ asset_url_for('images/favicon.png') }}">

        <link rel="pingback" href="https://webmention.io/braithwaite.io/xmlrpc">
        <link rel="webmention" href="https://webmention.io/braithwaite.io/webmention">

        <link rel="alternate" title="ATOM Feed" type="application/atom+xml" href="https://braithwaite.io{{ url_for('views.feed', feed_type='xml') }}">
        <link rel="alternate" title="JSON Feed" type="application/json" href="https://braithwaite.io{{ url_for('views.feed', feed_type='json') }}">

        {% block extra_head %}{% endblock %}
    {% endblock %}
    </head>
    <body class="b-io">
        <div class="c-site-title">
            <a href="{{ url_for('views.index') }}" class="c-site-title__link">
                <h1 class="c-site-title__heading">
                    <span class="c-site-title__braithwaite">
                        Braithwaite
                    </span>

                    <span class="c-site-title__io">I/O</span>
                </h1>
            </a>
        </div>

        <div class="c-page {% block extra_page_css %}{% endblock %}">
            {% block body %}{% endblock %}
        </div>

        <div class="c-footer h-card">
            <div class="c-footer__inner">
                <div class="c-footer__top">
                    <h2 class="c-footer__name p-name">
                        Myles Braithwaite
                    </h2>

                    <div class="c-footer__avatar">
                        <img class="c-footer__avatar-image u-photo"
                             src="{{ asset_url_for('images/avatar.svg') }}"
                             alt="Myles Braithwaite's Avatar"
                        >
                    </div>

                    <div class="c-footer__icon-group">
                        <a class="c-footer__icon c-footer__icon--twitter u-url"
                           rel="me"
                           href="https://twitter.com/mylesb"
                        >
                            <img class="c-footer__icon-image"
                                 src="{{ asset_url_for('images/twitter.svg') }}"
                                 alt="Twitter"
                            >
                        </a>

                        <a class="c-footer__icon c-footer__icon--github u-url"
                           rel="me"
                           href="https://github.com/myles"
                        >
                            <img class="c-footer__icon-image"
                                 src="{{ asset_url_for('images/github.svg') }}"
                                 alt="GitHub">
                        </a>

                        <a class="c-footer__icon c-footer__icon--facebook u-url"
                           rel="me"
                           href="https://facebook.com/mylesbraithwaite"
                        >
                            <img class="c-footer__icon-image"
                                 src="{{ asset_url_for('images/facebook.svg') }}"
                                 alt="Facebook"
                            >
                        </a>

                        <a class="c-footer__icon c-footer__icon--github u-url"
                           rel="me"
                           href="https://linkedin.com/in/mylesbraithwaite"
                        >
                            <img class="c-footer__icon-image"
                                 src="{{ asset_url_for('images/linkedin.svg') }}"
                                 alt="LinkedIn"
                            >
                        </a>
                    </div>
                </div>

                <div class="c-footer__copy">
                    <p>Myles Braithwaite lives in <span class="p-locality">Toronto</span> where he runs a small consulting company called <a class="p-org h-card" href="https://monkeyinyoursoul.com/">Monkey in your Soul</a> (you should hire him).</p>
                </div>

                <div class="c-footer__btn-group">
                    <a class="c-btn u-url" rel="me" href="https://mylesbraithwaite.com/">Blog</a>
                    <a class="c-btn u-url" rel="me" href="https://mylesb.ca/">Homepage</a>
                    <a class="c-btn u-email" rel="me" href="mailto:myles@braithwaite.io">Email</a>
                </div>
            </div>
        </div>

        {% block foot %}
        <script src="{{ asset_url_for('main.js') }}"></script>
        {% block extra_foot %}{% endblock %}
        {% endblock %}
    </body>
</html>

b_io/templates/index.html
{% extends "base.html" %}

{% block extra_page_css %}c-page--home{% endblock %}

{% block body %}
    <div class="b-home">
        <div class="b-home__notebook-list">
            {% for notebook in notebooks %}
            <a class="b-home__notebook-link" href="{{ notebook.url }}">
                <h2 class="b-home__notebook-title">
                    {{ notebook.name }}
                </h2>

                <p class="b-home__notebook-date">
                    {{ notebook.published.strftime('%-d %B %Y') }}
                </p>

                {% if notebook.summary %}
                <p class="b-home__notebook-summary">
                    {{ notebook.summary }}
                </p>
                {% endif %}
            </a>
            {% endfor %}
        </div>
    </div>
{% endblock %}

b_io/templates/notebook.html
{% extends "base.html" %}

{% block title %}{{ notebook.name }}{% endblock %}

{% block extra_head %}
    {% if notebook.hidden %}<meta name="robots" content="noindex">{% endif %}
{% endblock %}

{% block extra_page_css %}c-page--notebook{% endblock %}

{% block body %}
<div class="b-notebook h-entry">
    <div class="b-notebook__header">
        <h1 class="b-notebook__title p-name">
            <a class="b-notebook__url u-url" href="{{ notebook.url }}">
                {{ notebook.name }}
            </a>
        </h1>

        <h2 class="b-notebook__date dt-published" datetime="{{ notebook.published.isoformat() }}">{{ notebook.published.strftime('%d %B %Y') }}</h2>

        {% if notebook.summary %}
        <p class="b-notebook__summary p-summary">
            {{ notebook.summary | safe }}
        </p>
        {% endif %}
    </div>

    <div class="b-notebook__content c-jupyter e-content">
        {{ notebook.content | safe }}
    </div>
</div>
{% endblock %}